import type { Metadata } from 'next'
import { Noto_Sans_JP } from 'next/font/google'
import './globals.css'
import {
  NavigationMenu,
  NavigationMenuContent,
  NavigationMenuItem,
  NavigationMenuLink,
  NavigationMenuList,
  NavigationMenuTrigger,
  navigationMenuTriggerStyle
} from '@/components/ui/navigation-menu'
import {
  Sheet,
  SheetContent,
  SheetDescription,
  SheetFooter,
  SheetHeader,
  SheetTitle,
  SheetTrigger
} from '@/components/ui/sheet'

import { cn } from '@/lib/utils'
import Image from 'next/image'
import Link from 'next/link'
import { ChevronDown, ChevronRight, Menu } from 'lucide-react'
import { Button } from '@/components/ui/button'

const notoSansJP = Noto_Sans_JP({
  subsets: ['latin'],
  display: 'swap'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${notoSansJP.className} antialiased palt`}>
        <header className='flex justify-center w-full sticky top-0 bg-background/80 backdrop-blur-sm backdrop-saturate-200 px-4'>
          <div className='flex w-full max-w-7xl gap-3 justify-between py-4'>
            <Link href='/'>
              <Image
                src='/wasedule_icon.svg'
                width={36}
                height={36}
                alt='わせジュール'
              />
            </Link>
            <NavigationMenu className='hidden lg:block'>
              <NavigationMenuList>
                <NavigationMenuItem>
                  <NavigationMenuTrigger>使い方ガイド</NavigationMenuTrigger>
                  <NavigationMenuContent>
                    <ul className='grid gap-3 p-4 md:w-[400px] lg:w-[500px] lg:grid-cols-[.75fr_1fr]'>
                      <li className='row-span-3'>
                        <NavigationMenuLink asChild>
                          <a
                            className='flex h-full w-full select-none flex-col justify-end rounded-md bg-gradient-to-b from-muted/50 to-muted p-6 no-underline outline-none focus:shadow-md'
                            href='/'
                          >
                            <div className='h-6 w-6' />
                            <div className='mb-2 mt-4 text-lg font-medium'>
                              自動登録
                            </div>
                            <p className='text-sm leading-tight text-muted-foreground'>
                              Beautifully designed components built with Radix
                              UI and Tailwind CSS.
                            </p>
                          </a>
                        </NavigationMenuLink>
                      </li>
                      <NavigationMenuLink asChild>
                        <a
                          className={cn(
                            'block select-none space-y-1 rounded-md p-3 leading-none no-underline outline-none transition-colors hover:bg-accent hover:text-accent-foreground focus:bg-accent focus:text-accent-foreground'
                          )}
                        >
                          <div className='text-sm font-medium leading-none'>
                            課題の管理
                          </div>
                          <p className='line-clamp-2 text-sm leading-snug text-muted-foreground'>
                            Re-usable components built using Radix UI and
                            Tailwind CSS.
                          </p>
                        </a>
                      </NavigationMenuLink>
                      <NavigationMenuLink asChild>
                        <a
                          className={cn(
                            'block select-none space-y-1 rounded-md p-3 leading-none no-underline outline-none transition-colors hover:bg-accent hover:text-accent-foreground focus:bg-accent focus:text-accent-foreground'
                          )}
                        >
                          <div className='text-sm font-medium leading-none'>
                            スケジュールの管理
                          </div>
                          <p className='line-clamp-2 text-sm leading-snug text-muted-foreground'>
                            Re-usable components built using Radix UI and
                            Tailwind CSS.
                          </p>
                        </a>
                      </NavigationMenuLink>
                      <NavigationMenuLink asChild>
                        <a
                          className={cn(
                            'block select-none space-y-1 rounded-md p-3 leading-none no-underline outline-none transition-colors hover:bg-accent hover:text-accent-foreground focus:bg-accent focus:text-accent-foreground'
                          )}
                        >
                          <div className='text-sm font-medium leading-none'>
                            もっと活用する
                          </div>
                          <p className='line-clamp-2 text-sm leading-snug text-muted-foreground'>
                            Re-usable components built using Radix UI and
                            Tailwind CSS.
                          </p>
                        </a>
                      </NavigationMenuLink>
                    </ul>
                  </NavigationMenuContent>
                </NavigationMenuItem>
                <NavigationMenuItem>
                  <Link href='/socials' legacyBehavior passHref>
                    <NavigationMenuLink
                      className={navigationMenuTriggerStyle()}
                    >
                      メディア
                    </NavigationMenuLink>
                  </Link>
                </NavigationMenuItem>
                <NavigationMenuItem>
                  <Link href='/' legacyBehavior passHref>
                    <NavigationMenuLink
                      className={navigationMenuTriggerStyle()}
                    >
                      お問い合わせ
                    </NavigationMenuLink>
                  </Link>
                </NavigationMenuItem>
              </NavigationMenuList>
            </NavigationMenu>
            <Sheet>
              <SheetTrigger className='lg:hidden'>
                <Menu />
              </SheetTrigger>
              <SheetContent className='w-[240px] justify-center px-8'>
                <SheetHeader className='p-0'>
                  <SheetTitle className='text-zinc-300 text-xs'>
                    ナビゲーションメニュー
                  </SheetTitle>
                </SheetHeader>
                <ul className='flex flex-col gap-4 text-sm font-semibold'>
                  <div className='flex flex-col gap-4'>
                    <li>
                      <ChevronDown className='inline h-3' />
                      使い方ガイド
                    </li>
                    <li className='ml-10'>
                      <Link href=''>自動登録</Link>
                    </li>
                    <li className='ml-10'>
                      <Link href=''>課題の管理</Link>
                    </li>
                    <li className='ml-10'>
                      <Link href=''>スケジュールの管理</Link>
                    </li>
                    <li className='ml-10'>
                      <Link href=''>もっと活用する</Link>
                    </li>
                  </div>
                  <li className='ml-2'>
                    <Link href='/socials'>メディア</Link>
                  </li>
                  <li className='ml-2'>
                    <Link href=''>お問い合わせ</Link>
                  </li>
                </ul>
                <footer className='flex flex-col gap-3 text-zinc-300 text-xs my-8'>
                  <div className='flex justify-center flex-wrap max-w-7xl gap-4 opacity-15'>
                    <Link href=''>
                      <Image
                        src='/external-assets/x-logo/logo-black.png'
                        width={31}
                        height={31}
                        alt='公式X - @wasedule'
                        className='p-0.5'
                      />
                    </Link>
                    <Link href=''>
                      <Image
                        src='/external-assets/IG_brand_asset_pack_2023/01 Static Glyph/03 Black Glyph/Instagram_Glyph_Black.svg'
                        width={33}
                        height={33}
                        alt='公式Instagram - wasedule'
                      />
                    </Link>
                  </div>
                  <section className='flex flex-wrap gap-3'>
                    <Link href=''>プライバシーポリシー</Link>
                    <Link href=''>利用規約</Link>
                  </section>
                  <section className='w-full max-w-7xl text-end'>
                    <p>© 2024 わせジュール</p>
                  </section>
                </footer>
              </SheetContent>
            </Sheet>
          </div>
        </header>
        {children}
        <footer className='flex flex-col justify-center items-center px-4 py-8 gap-8'>
          <section
            className='flex flex-col lg:flex-row items-center
          gap-8 justify-between w-full max-w-4xl'
          >
            <Link href=''>
              <Image
                src='/wasedule_icon.svg'
                width={36}
                height={36}
                alt='わせジュール'
              />
            </Link>
            <div className='flex flex-wrap max-w-7xl gap-4'>
              <Link href=''>
                <Image
                  src='/external-assets/x-logo/logo-black.png'
                  width={31}
                  height={31}
                  alt='公式X - @wasedule'
                  className='p-0.5'
                />
              </Link>
              <Link href=''>
                <Image
                  src='/external-assets/IG_brand_asset_pack_2023/01 Static Glyph/03 Black Glyph/Instagram_Glyph_Black.svg'
                  width={33}
                  height={33}
                  alt='公式Instagram - wasedule'
                />
              </Link>
            </div>
          </section>
          <section className='flex flex-wrap max-w-7xl'>
            <Link href='' className='p-3 text-sm font-semibold'>
              プライバシーポリシー
            </Link>
            <Link href='' className='p-3 text-sm font-semibold'>
              利用規約
            </Link>
          </section>
          <section className='w-full max-w-7xl text-end'>
            <p className='text-sm font-semibold'>© 2024 わせジュール</p>
          </section>
        </footer>
      </body>
    </html>
  )
}
